### ISSUE TITLE
what version of python and flask to use?

### ISSUE THREAD

**Issue by turbulent0** [riad-azz/flask-template#1]
i've installed flask=2.3 and python=3.9 and it is not working

**Comment by riad-azz** [comment]
Hey, I am using Python >= 3.11 in the template. I can help you if you don't mind sharing the problem you have, I think its something to do with typing according to the version.

**Comment by riad-azz** [comment]
Okay an update, i tried the template and there was a problem with the **Flask-Login** extensions because **Werkzeug** versions after > 3.x.x made some changes [ImportError: cannot import name 'url_decode' from 'werkzeug.urls'](https://stackoverflow.com/questions/77215107/importerror-cannot-import-name-url-decode-from-werkzeug-urls).

I pushed a change and set the version in the `requirements.txt` to `Werkzeug==2.3.7` now it should work with no problem.

Let me know if you still have the same problem.
